rp.TNRdB = 10; % TNR in dB
rp.INRdB = 20; % INR in dB
rp.Nsnaps = 200;
rp.mu = 1e-8;
rp.p = 5;
rp.decay = 0;
rp.verbose = 0;
rp.mean_v = 0; % mean of complex-valued AWGN
rp.var_v = 1; % variance of complex-valued AWGN
rp.sin_theta_2 = -0.05;
rp.sin_theta_1 = 0;
rp.name = 'run1';